# Generated by Django 5.0.6 on 2024-08-04 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loanType', models.CharField(max_length=50)),
                ('loanRequestAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loanRequestDate', models.DateTimeField(auto_now_add=True)),
                ('loanDescription', models.CharField(max_length=200)),
                ('loanRepayDuration', models.CharField(max_length=30)),
                ('loanRepayPerMonth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loanPaymentDeadline', models.DateTimeField(blank=True, null=True)),
                ('loanStatus', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING')),
                ('referee', models.CharField(max_length=50)),
                ('loanRepaymentPlan', models.CharField(max_length=20)),
                ('amount_already_paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('amount_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='LoanVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_reason', models.CharField(max_length=200)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('loan_verified_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'loan_verification',
            },
        ),
    ]
